language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t vijayragavan/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vijayragavan/docker-react npm run test